### ISSUE TITLE
Properties of A* heuristic

### ISSUE THREAD

**Issue by cjay** [ChrisPenner/astar-monad#2]
The README states

>  Remember that A* heuristics should always be pessimistic (e.g. can over-estimate cost, but shouldn't UNDER estimate)

It should be the other way around. Or are you using a modified version of A* that has this property?

**Comment by ChrisPenner** [comment]
You're correct, the docs are backwards haha.

Regardless, I'd actually recommend using https://github.com/ennocramer/monad-dijkstra instead of this project, it's better maintained, runs faster, and has more features.
